---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Complete Markdown

```{r}
# 1) Load required packages

library('tidyverse')
library('minpack.lm')
library('viridis')
library('ggpubr')
library('ggExtra')

options(scipen = 999)
rm(list = ls())
```

```{r}
# 2) Set constants

start_year <- 1963 # first year of observed time series
stop_year <- 2018 # final year of observed time series
stop_year_fut = 2100 # final year of projections
btrigger = 97777 # MSY Btrigger management reference value
fmsy = 0.28 # FMSY management reference value
stock_code <- 'nsTmean' # code word required for subsetting past SST data
bar_low <- 2 # lower age class contributing to Fbar
bar_high <- 4 # upper age class contributing to Fbar
```

```{r}
# 3) Load and plot SST data (historical reconstructions and prjections)

assign('SST_NOAA', get(load('/home/jan/PhD/Data/Physical_Data/tot_sst.RData')))
sst <- as.data.frame(cbind(SST_NOAA$Year, eval(parse(text = paste0('SST_NOAA$', stock_code)))))
sst <- sst[sst$V1 %in% seq(start_year, stop_year, 1),]
names(sst) <- c('year', 'mean_sst') # load historical SST data

sst45 <- read.csv('/home/jan/PhD/Data/Physical_Data/Projections/sst45_north_sea.csv', sep = '\t') # load model hindcast and projections for RCP4.5 scenario (Peck et al., 2020)
sst85 <- read.csv('/home/jan/PhD/Data/Physical_Data/Projections/sst85_north_sea.csv', sep = '\t') # load model hindcast and projections for RCP8.5 scenario (Peck et al., 2020)

assign('SST_NOAA', get(load('/home/jan/PhD/Data/Physical_Data/tot_sst.RData'))) # load reconstructed historical data (Huang et al., 2017)

sst_obs_ref <- as.data.frame(cbind(SST_NOAA$Year, eval(parse(text = paste0('SST_NOAA$', stock_code))))) # select reconstructions for the North Sea only
sst_obs_ref <- sst_obs_ref[sst_obs_ref$V1 >= start_year,2]
sst_obs_ref <- sst_obs_ref[(length(sst_obs_ref)-(max(SST_NOAA$Year) - min(sst45$Year))):length(sst_obs_ref)] # limit reconstruction time series to match the temporal extent of the historical model data. This subset is used as "observation reference data set" for calculating the offset used in bias-correcting the projection data

sst45_mod_ref <- sst45$SST[sst45$Year <= max(SST_NOAA$Year)]
sst85_mod_ref <- sst85$SST[sst85$Year <= max(SST_NOAA$Year)] # subsetting a "model reference data set" for calculating the offset used in bias-correcting the projection data. These data consist of model hindcast and early projection data (for which reconstructions also exist)

sst45_corr <- -median(as.vector(as.matrix(sst45_mod_ref)) - sst_obs_ref)
sst85_corr <- -median(as.vector(as.matrix(sst85_mod_ref)) - sst_obs_ref) # calculate correction bias from "observation-" and "model reference data sets"

sst45 = sst45[sst45$Year >= stop_year,2] + sst45_corr
sst85 = sst85[sst85$Year >= stop_year,2] + sst85_corr # bias-correct model projections

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/sst_rcp45.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot() + 
    geom_line(aes(seq(2000,stop_year,length.out = nrow(sst)), sst$mean_sst), size = 1) + # plot historical and projected SST data (for RCP4.5 scenario)
    geom_line(aes(seq(stop_year+1,stop_year_fut-1,1), unlist(sst45[2:length(sst45)])), color = plasma(4)[3], size = 1) + 
    geom_vline(xintercept = 2029, linetype = 'dashed') + 
    geom_hline(yintercept = max(sst$mean_sst), color = 'red') + 
    ylim(min(sst$mean_sst), c(max(c(max(sst45), max(sst85))))) + theme_bw() + theme(text = element_text(size = 19)) + xlab('Time [a]') + ylab('SST [°C]') + scale_x_continuous(labels = c(seq(min(sst$year),2050,1)[seq(2000,stop_year,length.out = nrow(sst)) == 2000][1], 2025, 2050, 2075, 2100))
dev.off()

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/sst_rcp85.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot() + 
    geom_line(aes(seq(2000,stop_year,length.out = nrow(sst)), sst$mean_sst), size = 1) + # plot historical and projected SST data (for RCP8.5 scenario) 
    geom_line(aes(seq(stop_year+1,stop_year_fut-1,1), unlist(sst85[2:length(sst85)])), color = plasma(4)[2], size = 1) + 
    geom_vline(xintercept = 2029, linetype = 'dashed') + 
    geom_hline(yintercept = max(sst$mean_sst), color = 'red') + 
    ylim(min(sst$mean_sst), c(max(c(max(sst45), max(sst85))))) + theme_bw() + theme(text = element_text(size = 19)) + xlab('Time [a]') + ylab('SST [°C]') + scale_x_continuous(labels = c(seq(min(sst$year),2050,1)[seq(2000,stop_year,length.out = nrow(sst)) == 2000][1], 2025, 2050, 2075, 2100))
dev.off()
```

```{r}
# 4) Load projection outputs

bh_harvest <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/Harvest_Rate_Bevertonh_Focus.csv') # stock metrics for projections made with the Beverton-Holt SR model and harvest rate as policy metric
bh_harvest_params <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/Harvest_Rate_Bevertonh_Focus_Params.csv') # uncertain parameters and policies for projections made with the Beverton-Holt SR model and harvest rate as policy metric
bh_harvest <- as.data.frame(cbind(bh_harvest[,c(1,3:ncol(bh_harvest))], bh_harvest_params[,2:ncol(bh_harvest_params)])) # concatenate the two data sets

rk_harvest <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/Harvest_Rate_Ricker_Focus.csv') # stock metrics for projections made with the Ricker SR model and harvest rate as policy metric
rk_harvest_params <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/Harvest_Rate_Ricker_Focus_Params.csv') # uncertain parameters and policies for projections made with the Ricker SR model and harvest rate as policy metric
rk_harvest <- as.data.frame(cbind(rk_harvest[,c(1,3:ncol(rk_harvest))], rk_harvest_params[,2:ncol(rk_harvest_params)]))

bh_catch <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/Catch_Bevertonh.csv') # stock metrics for projections made with the Beverton-Holt SR model and fixed catch as policy metric
bh_catch_params <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/Catch_Bevertonh_Params.csv') # uncertain parameters and policies for projections made with the Beverton-Holt SR model and fixed catch as policy metric
bh_catch <- as.data.frame(cbind(bh_catch[,c(1,3:ncol(bh_catch))], bh_catch_params[,2:ncol(bh_catch_params)]))

rk_catch <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/Catch_Ricker.csv') # stock metrics for projections made with the Ricker SR model and fixed catch as policy metric
rk_catch_params <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/Catch_Ricker_Params.csv') # uncertain parameters and policies for projections made with the Ricker SR model and fixed catch as policy metric
rk_catch <- as.data.frame(cbind(rk_catch[,c(1,3:ncol(rk_catch))], rk_catch_params[,2:ncol(rk_catch_params)]))

names(rk_catch)[ncol(rk_harvest)-7] <- names(rk_harvest)[ncol(rk_harvest)-7] <- names(bh_catch)[ncol(rk_harvest)-7] <- names(bh_harvest)[ncol(rk_harvest)-7] <- 'alpha'
names(rk_catch)[ncol(rk_harvest)-6] <- names(rk_harvest)[ncol(rk_harvest)-6] <- names(bh_catch)[ncol(rk_harvest)-6] <- names(bh_harvest)[ncol(rk_harvest)-6] <- 'beta'
names(rk_catch)[ncol(rk_harvest)-5] <- names(rk_harvest)[ncol(rk_harvest)-5] <- names(bh_catch)[ncol(rk_harvest)-5] <- names(bh_harvest)[ncol(rk_harvest)-5] <- 'gamma'
names(rk_catch)[ncol(rk_harvest)-4] <- names(rk_harvest)[ncol(rk_harvest)-4] <- names(bh_catch)[ncol(rk_harvest)-4] <- names(bh_harvest)[ncol(rk_harvest)-4] <- 'manage_val'
names(rk_catch)[ncol(rk_harvest)] <- names(rk_harvest)[ncol(rk_harvest)] <- names(bh_catch)[ncol(rk_harvest)] <- names(bh_harvest)[ncol(rk_harvest)] <- 'RCP' # rename some of the columns in the data sets

dat <- rbind(rk_catch, bh_catch, rk_harvest, bh_harvest) # concatenate the four data sets into one

dat$sr_mod <- c(rep('ricker', times = nrow(dat)/4), rep('beverton holt', times = nrow(dat)/4), rep('ricker', times = nrow(dat)/4), rep('beverton holt', times = nrow(dat)/4))
dat$manage_cat <- c(rep('catch', times = nrow(dat)/2), rep('harvest', times = nrow(dat)/2)) # add columns specifying the SR model and the polic metric

rm(rk_catch, bh_catch, rk_harvest, bh_harvest)
gc()
```

```{r}
# 5) Calculate Fbar and re-arrange the data

for(i in 2029:(stop_year_fut-1)){
  mean_f <- rowSums(do.call(cbind, lapply(seq(bar_low,bar_high,1), function(x){eval(parse(text = paste0("dat$f_age_",x,"_year_", i)))}))) / length(seq(bar_low,bar_high,1))
  eval(parse(text = paste0("dat$mean_f_", i, "<- mean_f")))
} # calculate Fbar: the mean F over age classes 2-4

catch_realized <- dat%>%select(c(manage_cat, manage_val, alpha, sr_mod, RCP, contains('crw')))%>%gather(contains('crw'), key = 'year', value = 'catch_realized')%>%select(c(manage_cat, manage_val, alpha, sr_mod, RCP, year, catch_realized)) # subset realized-catch data and bring them into long format
catch_realized$year <- as.numeric(substr(catch_realized$year, 10, 15))

harvest_realized <- dat%>%select(c(manage_cat, manage_val, alpha, sr_mod, RCP, contains('hrr')))%>%gather(contains('hrr'), key = 'year', value = 'harvest_realized')%>%select(c(manage_cat, manage_val, alpha, sr_mod, RCP, year, harvest_realized)) # subset realized-harvest-rate data and bring them into long format
harvest_realized$year <- as.numeric(substr(harvest_realized$year, 10, 15))

profit <- dat%>%select(c(manage_cat, manage_val, alpha, sr_mod, RCP, contains('profit')))%>%gather(contains('profit'), key = 'year', value = 'profit')%>%select(c(manage_cat, manage_val, alpha, sr_mod, RCP, year, profit)) # subset profit data and bring them into long format
profit$year <- as.numeric(substr(profit$year, 8, 15))

dat <- dat%>%select(-c(contains('crw'), contains('hrr'), contains('profit'), contains('crn_age'), contains('n_age_2'), contains('n_age_3'), contains('n_age_4'), contains('n_age_5'), contains('n_age_6'), contains('f_age')))

dat <- dat%>%gather(c(contains("20"), contains("21")), key = 'metric_year', value = 'val') # bring data into long format (with respect to output metrics SSB and Fbar)
dat$year <- as.numeric(substr(dat$metric_year, nchar(dat$metric_year)-3, nchar(dat$metric_year)))
dat$metric <- substr(dat$metric_year, 1, nchar(dat$metric_year)-5)

dat <- full_join(dat, catch_realized, by = c("year", "alpha", "RCP", "manage_val", "sr_mod", "manage_cat"))
dat <- full_join(dat, harvest_realized, by = c("year", "alpha", "RCP", "manage_val", "sr_mod", "manage_cat"))
dat <- full_join(dat, profit, by = c("year", "alpha", "RCP", "manage_val", "sr_mod", "manage_cat")) # re-join the subsets with the original data frame
```

```{r, fig.width=5, fig.height=5}
# 6) Display the uncertain SR-model samples (i.e., the different SR-model parameterizations)

sr_dat <- read.table("/home/jan/PhD/Data/Lindegren_Papers/Cod_North_Sea/R_SSB.txt",header=T) # load historical SSB- and recruitment data

x <- sr_dat$SSB[1:55]
x2 <- sst$mean_sst[1:55]
y <- sr_dat$Recruits[2:56] # set up SSB, SST and recruitment as input data for the SR models


subs <- dat[dat$sr_mod == 'ricker',] # subset the uncertain Ricker models
pars <- distinct(subs%>%select(alpha, beta, gamma)) # isolate the different uncertain parameter sets

mod <- nlsLM(log(y/x) ~ log_ac - exp(log_bc) * x - cc * x2, control = list(maxiter = Inf)) # set up the Ricker-model object (see script on SR-model fitting for details)

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/ssb_r_curves_ricker.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
plot(x/1000, y/1000, ylim = c(0, 3500), type = 'n', xlab = 'SSB [kt]', ylab = expression(paste('Recruitment [',10^{6},']'))) # plot SSB- and recruitment data
for(i in 1:nrow(pars)){ # loop over all parameter sets
  mod$m$setPars(c(pars$alpha[i], pars$beta[i], pars$gamma[i])) # load parameter set #i into the model object
  
  pred <- seq(min(x), max(x), length.out = 100) * exp(predict(mod, newdata = list('x' = seq(min(x), max(x), length.out = 100), 'x2' = mean(x2)))) # predict recruitment for all historical SSB data and the mean historical SST

  lines(seq(min(x), max(x), length.out = 100) / 1000, pred / 1000, col = colours()[i], lwd = 0.5) # add a line with the predictions (i.e.,partial effect of SSB for this set of SR-model parameters) to the SSB-recruitment plot
}
points(x/1000, y/1000, pch = 16)
dev.off()

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/sst_r_curves_ricker.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
plot(x2, y/1000, ylim = c(0, 3500), type = 'n', xlab = 'SST [°C]', ylab = expression(paste('Recruitment [',10^{6},']'))) # plot SST- and recruitment data
for(i in 1:nrow(pars)){ # loop over all parameter sets
  mod$m$setPars(c(pars$alpha[i], pars$beta[i], pars$gamma[i])) # load parameter set #i into the model object

  pred <- mean(x) * exp(predict(mod, newdata = list('x' = mean(x), 'x2' = seq(min(x2), max(x2), length.out = 100)))) # predict recruitment for all historical SST data and the mean historical SSB
  
  lines(seq(min(x2), max(x2), length.out = 100), pred / 1000, col = colours()[i], lwd = 0.5) # add a line with the predictions (i.e.,partial effect of SST for this set of SR-model parameters) to the SST-recruitment plot
}
points(x2, y/1000, pch = 16)
dev.off()


subs <- dat[dat$sr_mod == 'beverton holt',]
pars <- distinct(subs%>%select(alpha, beta, gamma))

mod <- nlsLM(log(y) ~ cc * x2 + (log_ac + log(x)) - log(1 + exp(log_bc + log(x))), control = list(maxiter = Inf))

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/ssb_r_curves_bevertonh.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
plot(x/1000, y/1000, ylim = c(0, 3500), type = 'n', xlab = 'SSB [kt]', ylab = expression(paste('Recruitment [',10^{6},']')))
for(i in 1:nrow(pars)){
  mod$m$setPars(c(pars$gamma[i], pars$alpha[i], pars$beta[i]))
  
  pred <- exp(predict(mod, newdata = list('x' = seq(min(x), max(x), length.out = 100), 'x2' = mean(x2))))
  
  lines(seq(min(x), max(x), length.out = 100) / 1000, pred / 1000, col = colours()[i], lwd = 0.5)
}
points(x/1000, y/1000, pch = 16)
dev.off()

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/sst_r_curves_bevertonh.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
plot(x2, y/1000, ylim = c(0, 3500), type = 'n', xlab = 'SST [°C]', ylab = expression(paste('Recruitment [',10^{6},']')))
for(i in 1:nrow(pars)){
  mod$m$setPars(c(pars$gamma[i], pars$alpha[i], pars$beta[i]))
  
  pred <- exp(predict(mod, newdata = list('x' = mean(x), 'x2' = seq(min(x2), max(x2), length.out = 100))))
  
  lines(seq(min(x2), max(x2), length.out = 100), pred / 1000, col = colours()[i], lwd = 0.5)
}
points(x2, y/1000, pch = 16)
dev.off() # same operations for the Beverton-Holt SR model
```

```{r}
# 8) Check for scenarios in which intended catch exceeds realized catch, and whether such periods are persistent and / or lead to stock collapse

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/realizedexploit_catch.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(dat%>%ungroup()%>%filter(year < max(year) & manage_cat == 'catch' & (round(manage_val) != round(catch_realized) & round(catch_realized) != 0))%>%select(year, alpha, sr_mod, RCP, manage_val, catch_realized)%>%distinct()) + 
  geom_tile(aes(year, interaction(manage_val, alpha, sr_mod, RCP)), size = 0.5, show.legend = F) + 
  geom_tile(data = dat%>%ungroup()%>%filter(year < max(year) & manage_cat == 'catch' & (round(manage_val) != round(catch_realized) & round(catch_realized) == 0))%>%group_by(manage_val, sr_mod, alpha, RCP)%>%filter(year == min(year))%>%ungroup()%>%select(year, alpha, sr_mod, RCP, manage_val, catch_realized)%>%distinct(), aes(year, interaction(manage_val, alpha, sr_mod, RCP)), fill = 'yellow', show.legend = F) + 
  xlab('Time [a]') + ylab('Scenario') + theme_dark() + theme(text = element_text(size = 15)) + theme(axis.text.y = element_blank(), axis.ticks.y = element_line(color = 'lightgray')) + 
  xlim(c(min(dat$year), max(dat$year)-1))
dev.off()

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/realizedexploit_harvest.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(dat%>%ungroup()%>%filter(year < max(year) & manage_cat == 'harvest' & (round(manage_val, 2) != round(harvest_realized, 2) & round(harvest_realized, 2) != 0))%>%select(year, alpha, sr_mod, RCP, manage_val, harvest_realized)%>%distinct()) + 
  geom_tile(aes(year, interaction(manage_val, alpha, sr_mod, RCP)), size = 0.5, show.legend = F) + 
  geom_tile(data = dat%>%ungroup()%>%filter(year < max(year) & manage_cat == 'harvest' & (round(manage_val, 2) != round(harvest_realized, 2) & round(harvest_realized, 2) == 0))%>%group_by(manage_val, sr_mod, alpha, RCP)%>%filter(year == min(year))%>%ungroup()%>%select(year, alpha, sr_mod, RCP, manage_val, harvest_realized)%>%distinct(), aes(year, interaction(manage_val, alpha, sr_mod, RCP)), fill = 'yellow', show.legend = F) + 
  xlab('Time [a]') + ylab('Scenario') + theme_dark() + theme(text = element_text(size = 15)) + theme(axis.text.y = element_blank(), axis.ticks.y = element_line(color = 'lightgray')) + 
  xlim(c(min(dat$year), max(dat$year)-1))
dev.off()
```

```{r}
# 7) Plot the median projected recruitment and SSB over projection years for both climate scenarios

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/med_recruitment.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(dat%>%ungroup()%>%filter(metric == 'n_age_1_year')%>%select(year, RCP, val)%>%group_by(year, RCP)%>%mutate(md_recr = median(val), q25_recr= quantile(val, 0.25, names = F), q75_recr = quantile(val, 0.75, names = F))%>%ungroup()%>%select(-val)%>%distinct()) + 
  geom_ribbon(aes(year, ymin = q25_recr / 1e+3, ymax = q75_recr / 1e+3, fill = RCP, group = RCP), alpha = 0.5, show.legend = F) + 
  geom_line(aes(year, md_recr / 1e+3, color = RCP, group = RCP), show.legend = F) + 
  xlab('Year') + ylab(expression(paste('Recruits [',10^{6},']'))) + theme_bw() + theme(text = element_text(size = 15)) + 
  scale_color_viridis(discrete = T, direction = -1, option = 'plasma', begin = 0.2, end = 0.8) + scale_fill_viridis(discrete = T, direction = -1, option = 'plasma', begin = 0.2, end = 0.8)
dev.off()

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/med_ssb.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(dat%>%ungroup()%>%filter(metric == 'ssb_year')%>%select(year, RCP, val)%>%group_by(year, RCP)%>%mutate(md_ssb = median(val), q25_ssb = quantile(val, 0.25, names = F), q75_ssb = quantile(val, 0.75, names = F))%>%ungroup()%>%select(-val)%>%distinct()) + 
  geom_ribbon(aes(year, ymin = q25_ssb / 1e+3, ymax = q75_ssb / 1e+3, fill = RCP, group = RCP), alpha = 0.5, show.legend = F) + 
  geom_line(aes(year, md_ssb / 1e+3, color = RCP, group = RCP), show.legend = F) + 
  xlab('Year') + ylab('SSB [kt]') + theme_bw() + theme(text = element_text(size = 15)) + 
  scale_color_viridis(discrete = T, direction = -1, option = 'plasma', begin = 0.2, end = 0.8) + scale_fill_viridis(discrete = T, direction = -1, option = 'plasma', begin = 0.2, end = 0.8)
dev.off()
```

```{r}
dat <- dat[dat$metric != 'n_age_1_year',]
```

```{r, fig.width=5, fig.height=5}
# 8) Load and plot modeled historical profit data

profit_past <- read.csv('/home/jan/PhD/EMA/North_Sea_Paper/profit_north_sea.csv') # load modeled historical profit data (calculated with economic model presented by Schenk et al. (in prep.)) (see model script for details)

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/past_profit.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(profit_past) + 
  geom_line(aes(year, profit/1e+6)) + 
  xlab('Time [a]') + ylab('Profit [million Euros]') + 
  theme_bw() + theme(text = element_text(size = 15)) # plot the modeled historical profit data
dev.off()

mn_past_profit <- 107.97 # set custom profitability reference point (average profit of years 2000-2019; see model script for details)
```

```{r}
# 9) Calculate sustainability- and profitability risks

dat <- dat%>%select(year, sr_mod, manage_cat, manage_val, alpha, beta, gamma, metric, val, RCP, profit, catch_realized, harvest_realized)%>%spread(key = metric, value = val) # subset and re-arrange variables required for risk calculation

dat <- dat%>%ungroup()%>%group_by(manage_cat, year, manage_val, alpha, sr_mod, RCP)%>%mutate(
  risk_both = ssb_year <= btrigger | mean_f > fmsy, 
  profit_risk = profit < mn_past_profit, 
  harvest_fail = round(harvest_realized, 2) < round(manage_val, 2),
  catch_fail = round(catch_realized) < round(manage_val)) # check whether i) SSB equals to or is lower than MSY Btrigger and / or Fbar exceeds Fmsy, ii) profit is lower than the custom reference profit, iii) realized catch is lower than intended catch (i.e. the catch level that the model was forced with), iv) whether realized harvest rate is lower than intended harvest rate (i.e. the harvest-rate level that the model was forced with). The check returns logical values that will be aggregated later to calculate the risks

dat$harvest_fail[dat$manage_cat == 'catch'] <- NA
dat$catch_fail[dat$manage_cat == 'harvest'] <- NA

catch_intrvs <- seq(0, min(c(max(dat$manage_val[dat$manage_cat == 'catch' & dat$sr_mod == 'ricker'], na.rm = T), max(dat$manage_val[dat$manage_cat == 'catch' & dat$sr_mod == 'beverton holt'], na.rm = T))), length.out = 21)[2:21]
hrv_intrvs <- seq(0, min(c(max(dat$manage_val[dat$manage_cat == 'harvest' & dat$sr_mod == 'ricker'], na.rm = T), max(dat$manage_val[dat$manage_cat == 'harvest' & dat$sr_mod == 'beverton holt'], na.rm = T))), length.out = 21)[2:21] # the fact that separate model runs with different random policies were conducted for the different SR models means that the data need to be aggregated to integrate over the different SR models. 20 bins of equal ranges of catch and harvest rate are therefore set up, and assigned to the output data corresponding to the levels of intended catch and intended harvest rate

dat$manage_val_class[dat$manage_val < catch_intrvs[1] & dat$manage_cat == 'catch'] <- catch_intrvs[1]
dat$manage_val_class[dat$manage_val >= catch_intrvs[1] & dat$manage_val < catch_intrvs[2] & dat$manage_cat == 'catch'] <- catch_intrvs[2]
dat$manage_val_class[dat$manage_val >= catch_intrvs[2] & dat$manage_val < catch_intrvs[3] & dat$manage_cat == 'catch'] <- catch_intrvs[3]
dat$manage_val_class[dat$manage_val >= catch_intrvs[3] & dat$manage_val < catch_intrvs[4] & dat$manage_cat == 'catch'] <- catch_intrvs[4]
dat$manage_val_class[dat$manage_val >= catch_intrvs[4] & dat$manage_val < catch_intrvs[5] & dat$manage_cat == 'catch'] <- catch_intrvs[5]
dat$manage_val_class[dat$manage_val >= catch_intrvs[5] & dat$manage_val < catch_intrvs[6] & dat$manage_cat == 'catch'] <- catch_intrvs[6]
dat$manage_val_class[dat$manage_val >= catch_intrvs[6] & dat$manage_val < catch_intrvs[7] & dat$manage_cat == 'catch'] <- catch_intrvs[7]
dat$manage_val_class[dat$manage_val >= catch_intrvs[7] & dat$manage_val < catch_intrvs[8] & dat$manage_cat == 'catch'] <- catch_intrvs[8]
dat$manage_val_class[dat$manage_val >= catch_intrvs[8] & dat$manage_val < catch_intrvs[9] & dat$manage_cat == 'catch'] <- catch_intrvs[9]
dat$manage_val_class[dat$manage_val >= catch_intrvs[9] & dat$manage_val < catch_intrvs[10] & dat$manage_cat == 'catch'] <- catch_intrvs[10]
dat$manage_val_class[dat$manage_val >= catch_intrvs[10] & dat$manage_val < catch_intrvs[11] & dat$manage_cat == 'catch'] <- catch_intrvs[11]
dat$manage_val_class[dat$manage_val >= catch_intrvs[11] & dat$manage_val < catch_intrvs[12] & dat$manage_cat == 'catch'] <- catch_intrvs[12]
dat$manage_val_class[dat$manage_val >= catch_intrvs[12] & dat$manage_val < catch_intrvs[13] & dat$manage_cat == 'catch'] <- catch_intrvs[13]
dat$manage_val_class[dat$manage_val >= catch_intrvs[13] & dat$manage_val < catch_intrvs[14] & dat$manage_cat == 'catch'] <- catch_intrvs[14]
dat$manage_val_class[dat$manage_val >= catch_intrvs[14] & dat$manage_val < catch_intrvs[15] & dat$manage_cat == 'catch'] <- catch_intrvs[15]
dat$manage_val_class[dat$manage_val >= catch_intrvs[15] & dat$manage_val < catch_intrvs[16] & dat$manage_cat == 'catch'] <- catch_intrvs[16]
dat$manage_val_class[dat$manage_val >= catch_intrvs[16] & dat$manage_val < catch_intrvs[17] & dat$manage_cat == 'catch'] <- catch_intrvs[17]
dat$manage_val_class[dat$manage_val >= catch_intrvs[17] & dat$manage_val < catch_intrvs[18] & dat$manage_cat == 'catch'] <- catch_intrvs[18]
dat$manage_val_class[dat$manage_val >= catch_intrvs[18] & dat$manage_val < catch_intrvs[19] & dat$manage_cat == 'catch'] <- catch_intrvs[19]
dat$manage_val_class[dat$manage_val >= catch_intrvs[19] & dat$manage_cat == 'catch'] <- catch_intrvs[20] # assigning the catch bins to the data

dat$manage_val_class[dat$manage_val < hrv_intrvs[1] & dat$manage_cat == 'harvest'] <- hrv_intrvs[1]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[1] & dat$manage_val < hrv_intrvs[2] & dat$manage_cat == 'harvest'] <- hrv_intrvs[2]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[2] & dat$manage_val < hrv_intrvs[3] & dat$manage_cat == 'harvest'] <- hrv_intrvs[3]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[3] & dat$manage_val < hrv_intrvs[4] & dat$manage_cat == 'harvest'] <- hrv_intrvs[4]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[4] & dat$manage_val < hrv_intrvs[5] & dat$manage_cat == 'harvest'] <- hrv_intrvs[5]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[5] & dat$manage_val < hrv_intrvs[6] & dat$manage_cat == 'harvest'] <- hrv_intrvs[6]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[6] & dat$manage_val < hrv_intrvs[7] & dat$manage_cat == 'harvest'] <- hrv_intrvs[7]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[7] & dat$manage_val < hrv_intrvs[8] & dat$manage_cat == 'harvest'] <- hrv_intrvs[8]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[8] & dat$manage_val < hrv_intrvs[9] & dat$manage_cat == 'harvest'] <- hrv_intrvs[9]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[9] & dat$manage_val < hrv_intrvs[10] & dat$manage_cat == 'harvest'] <- hrv_intrvs[10]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[10] & dat$manage_val < hrv_intrvs[11] & dat$manage_cat == 'harvest'] <- hrv_intrvs[11]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[11] & dat$manage_val < hrv_intrvs[12] & dat$manage_cat == 'harvest'] <- hrv_intrvs[12]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[12] & dat$manage_val < hrv_intrvs[13] & dat$manage_cat == 'harvest'] <- hrv_intrvs[13]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[13] & dat$manage_val < hrv_intrvs[14] & dat$manage_cat == 'harvest'] <- hrv_intrvs[14]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[14] & dat$manage_val < hrv_intrvs[15] & dat$manage_cat == 'harvest'] <- hrv_intrvs[15]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[15] & dat$manage_val < hrv_intrvs[16] & dat$manage_cat == 'harvest'] <- hrv_intrvs[16]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[16] & dat$manage_val < hrv_intrvs[17] & dat$manage_cat == 'harvest'] <- hrv_intrvs[17]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[17] & dat$manage_val < hrv_intrvs[18] & dat$manage_cat == 'harvest'] <- hrv_intrvs[18]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[18] & dat$manage_val < hrv_intrvs[19] & dat$manage_cat == 'harvest'] <- hrv_intrvs[19]
dat$manage_val_class[dat$manage_val >= hrv_intrvs[19] & dat$manage_cat == 'harvest'] <- hrv_intrvs[20] # assigning the harvest-rate bins to the data

dat <- dat[dat$year >= 2030,]
dat <- dat[dat$year < max(dat$year),]

dat$decade_class[(dat$year >= 2029) & (dat$year < 2050)] <- 'Mid-century (2030-2049)'
dat$decade_class[dat$year >= 2050] <- 'Late century (2050-2099)' # data are grouped into two projection periods, which correspond to the onset of more frequent encounters of novel climate conditions, which is in appx. 2050

dat <- dat%>%group_by(manage_cat, manage_val_class, decade_class)%>%mutate(
  risk_both_mn = mean(risk_both),
  profit_risk_mn = mean(profit_risk, na.rm = T),
  perc_harvest_fail = mean(harvest_fail, na.rm=T),
  prec_catch_fail = mean(catch_fail, na.rm=T)
  ) # calculate sustainability risk, profitability risk, the risk of realized catch falling below intended catch, and the risk of realized harvest rate falling below intended harvest rate. This is achieved by dividing the sum of logical checks against reference values (see above) by the total number of uncertain scenarios (in this case, separately for each policy metric, policy level and projection period). The result is a percentage value of "failing" projections, i.e. a risk value
```

```{r, fig.height=5, fig.width=5}
# 10) Plotting the risks and the trade-off analysis

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/sust_risk_catch.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(distinct(dat%>%filter(manage_cat == 'catch')%>%select(manage_val_class, decade_class, risk_both_mn))) + geom_line(aes(manage_val_class/1e+3, risk_both_mn*100, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), show.legend = F) + xlab('Catch [kt]') + ylab('Sustainability risk [%]') + scale_color_viridis(direction = -1, 'Period', option = 'plasma', discrete = T, begin = 0.2, end = 0.8) + theme_bw() + theme(text = element_text(size = 15)) + ylim(c(0,100))
dev.off()

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/sust_risk_harvest.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(distinct(dat%>%filter(manage_cat == 'harvest')%>%select(manage_val_class, decade_class, risk_both_mn))) + geom_line(aes(manage_val_class*100, risk_both_mn*100, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), show.legend = F) + xlab('Harvest rate [%]') + ylab('Sustainability risk [%]') + scale_color_viridis(direction = -1, 'Period', option = 'plasma', discrete = T, begin = 0.2, end = 0.8) + theme_bw() + theme(text = element_text(size = 15)) + ylim(c(0,100))
dev.off() # plotting sustainability risk, for each projection period, for projections done with i) fixed catch and ii) fixed harvest rate

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/profit_risk_catch.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(distinct(dat%>%filter(manage_cat == 'catch')%>%select(manage_val_class, profit_risk_mn, decade_class))) + geom_line(aes(manage_val_class/1e+3, profit_risk_mn*100, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), show.legend = F) + xlab('Catch [kt]') + ylab('Profitability risk [%]') + scale_color_viridis(direction = -1, 'Period', option = 'plasma', discrete = T, begin = 0.2, end = 0.8) + theme_bw() + theme(text = element_text(size = 15)) + ylim(c(0,100))
dev.off()

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/profit_risk_harvest.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(distinct(dat%>%filter(manage_cat == 'harvest')%>%select(manage_val_class, profit_risk_mn, decade_class))) + geom_line(aes(manage_val_class*100, profit_risk_mn*100, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), show.legend = F) + xlab('Harvest rate [%]') + ylab('Profitability risk [%]') + scale_color_viridis(direction = -1, 'Period', option = 'plasma', discrete = T, begin = 0.2, end = 0.8) + theme_bw() + theme(text = element_text(size = 15)) + ylim(c(0,100))
dev.off() # plotting profitability risk, for each projection period, for projections done with i) fixed catch and ii) fixed harvest rate

 best_troffs <- dat%>%ungroup()%>%select(manage_cat, decade_class, manage_val_class, risk_both_mn, profit_risk_mn)%>%group_by(manage_cat, decade_class, manage_val_class)%>%summarize(add_risk = profit_risk_mn + risk_both_mn)%>%ungroup()%>%group_by(manage_cat, decade_class)%>%filter(add_risk == min(add_risk))%>%distinct() # calculate the policy levels associated with "best trade-off", i.e. the level of intended catch and intended harvest rate yielding the lowest additive risks (sustainability- and profitability risks)
 
best_troffs <- best_troffs%>%ungroup()%>%select(-add_risk)%>%rename(best_manage = manage_val_class)
dat <- full_join(dat, best_troffs, by = c('manage_cat', 'decade_class'))
print(best_troffs)

x_range <- seq(quantile(seq(0, 100), 0.1), quantile(seq(0, 100), 0.9))

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/tradeoff_catch.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(distinct(dat%>%group_by(manage_cat, manage_val_class, decade_class)%>%filter(manage_cat == 'catch')%>%select(risk_both_mn, profit_risk_mn, decade_class, best_manage))) + 
    geom_line(aes(risk_both_mn*100, profit_risk_mn*100, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), size = 1, show.legend = F) + 
    geom_segment(aes(risk_both_mn*100, profit_risk_mn*100, yend = 0, xend = (manage_val_class/1e+3) * (max(x_range)-min(x_range)) / max(manage_val_class/1e+3) + min(x_range), color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)')), size = round(manage_val_class) == round(best_manage)), alpha = 0.5, show.legend = F) + 
    geom_line(data = data.frame('x' = c(min((dat$manage_val_class[dat$manage_cat=='catch']/1e+3) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) + min(x_range)), (max(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) + min(x_range)), 'y' = c(0,0)), aes(x, y)) + 
    geom_text(data = data.frame('x' = quantile(seq(min((dat$manage_val_class[dat$manage_cat=='catch']/1e+3) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) + min(x_range)), (max(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) + min(x_range)), c(0, 1/3, 2/3, 1)), 'z' = round(quantile(seq((min(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3), (max(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3)), c(0, 1/3, 2/3, 1)))), aes(x, -5, label = z)) + 
    geom_segment(data = data.frame('x' = quantile(seq(min((dat$manage_val_class[dat$manage_cat=='catch']/1e+3) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) + min(x_range)), (max(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) + min(x_range)), c(0, 1/3, 2/3, 1)), 'z' = quantile(seq(min((dat$manage_val_class[dat$manage_cat=='catch']/1e+3) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) + min(x_range)), (max(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='catch'])/1e+3) + min(x_range)), c(0, 1/3, 2/3, 1))), aes(x, -3, xend = z, yend = 0)) + 
    annotate('text', x = (max(x_range)-min(x_range))/2 + min(x_range), y = -10, label = 'Catch [kt]') + 
    xlim(c(0,100)) + theme_bw() + theme(text = element_text(size = 15)) + xlab('Sustainability risk [%]') + ylab('Profitability risk [%]') + scale_color_viridis('Period', discrete = T, direction = -1, option = 'plasma', begin = 0.2, end = 0.8) + ylim(c(-10,100)) + scale_size_manual(values = c(0.3,1))
dev.off() # plot the relationship between profitability- and sustainability risk, and the relationship of the two risk types to the level of intended catch. The "best trade-off" is also plotted

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/tradeoff_harvest.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(distinct(dat%>%group_by(manage_cat, manage_val_class, decade_class)%>%filter(manage_cat == 'harvest')%>%select(risk_both_mn, profit_risk_mn, decade_class, best_manage))) + 
    geom_line(aes(risk_both_mn*100, profit_risk_mn*100, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), size = 1, show.legend = F) + 
    geom_segment(aes(risk_both_mn*100, profit_risk_mn*100, yend = 0, xend = (manage_val_class*100) * (max(x_range)-min(x_range)) / max(manage_val_class*100) + min(x_range), color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)')), size = round(manage_val_class, 2) == round(best_manage, 2)), alpha = 0.5, show.legend = F) + 
    geom_line(data = data.frame('x' = c(min((dat$manage_val_class[dat$manage_cat=='harvest']*100) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='harvest'])*100) + min(x_range)), (max(dat$manage_val_class[dat$manage_cat=='harvest'])*100) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='harvest'])*100) + min(x_range)), 'y' = c(0,0)), aes(x, y)) + 
    geom_text(data = data.frame('x' = quantile(seq(min((dat$manage_val_class[dat$manage_cat=='harvest']*100) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='harvest'])*100) + min(x_range)), (max(dat$manage_val_class[dat$manage_cat=='harvest'])*100) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='harvest'])*100) + min(x_range)), c(0, 1/3, 2/3, 1)), 'z' = round(quantile(seq((min(dat$manage_val_class[dat$manage_cat=='harvest'])*100), (max(dat$manage_val_class[dat$manage_cat=='harvest'])*100)), c(0, 1/3, 2/3, 1)))), aes(x, -5, label = z)) + 
    geom_segment(data = data.frame('x' = quantile(seq(min((dat$manage_val_class[dat$manage_cat=='harvest']*100) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='harvest'])*100) + min(x_range)), (max(dat$manage_val_class[dat$manage_cat=='harvest'])*100) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='harvest'])*100) + min(x_range)), c(0, 1/3, 2/3, 1)), 'z' = quantile(seq(min((dat$manage_val_class[dat$manage_cat=='harvest']*100) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='harvest'])*100) + min(x_range)), (max(dat$manage_val_class[dat$manage_cat=='harvest'])*100) * (max(x_range)-min(x_range)) / max(unique(dat$manage_val_class[dat$manage_cat=='harvest'])*100) + min(x_range)), c(0, 1/3, 2/3, 1))), aes(x, -3, xend = z, yend = 0)) + 
    annotate('text', x = (max(x_range)-min(x_range))/2 + min(x_range), y = -10, label = 'Harvest rate [%]') + 
    xlim(c(0,100)) + theme_bw() + theme(text = element_text(size = 15)) + xlab('Sustainability risk [%]') + ylab('Profitability risk [%]') + scale_color_viridis('Period', discrete = T, direction = -1, option = 'plasma', begin = 0.2, end = 0.8) + ylim(c(-10,100)) + scale_size_manual(values = c(0.3,1))
dev.off() # plot the relationship between profitability- and sustainability risk, and the relationship of the two risk types to the level of intended harvest rate. The "best trade-off" is also plotted

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/intendvsreal_catch.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(distinct(dat%>%ungroup()%>%filter(manage_cat == 'catch')%>%select(decade_class, prec_catch_fail, manage_val_class))) + 
  geom_line(aes(manage_val_class/1e+3, prec_catch_fail*100, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), show.legend = F) +
  xlab('Intended catch [kt]') + ylab('Realized catch < \nintended catch [%]') + scale_color_viridis(direction = -1, 'Period', option = 'plasma', discrete = T, begin = 0.2, end = 0.8) + theme_bw() + theme(text = element_text(size = 15)) + ylim(c(0,100)) 
dev.off() # plot the relative number of cases where realized catch is lower than intended catch, against the level of intended catch

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/intendvsreal_harvest.tiff",
     width = 5,height = 5,compression = "lzw",res = 600, units = "in")
ggplot(distinct(dat%>%ungroup()%>%filter(manage_cat == 'harvest')%>%select(decade_class, perc_harvest_fail, manage_val_class))) + 
  geom_line(aes(manage_val_class*100, perc_harvest_fail*100, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), show.legend = F) +
  xlab('Harvest rate [%]') + ylab('Realized harvest rate < \nintended harvest rate [%]') + scale_color_viridis(direction = -1, 'Period', option = 'plasma', discrete = T, begin = 0.2, end = 0.8) + theme_bw() + theme(text = element_text(size = 15)) + ylim(c(0,100)) 
dev.off() # plot the relative number of cases where realized harvest rate is lower than intended harvest rate, against the level of intended harvest rate

ggplot(dat%>%ungroup()%>%filter(catch_fail == T & year < max(year) & manage_cat == 'catch')%>%select(manage_val, decade_class, catch_realized)%>%distinct()%>%group_by(manage_val, decade_class)%>%summarize(md_ct_realized = median(catch_realized, na.rm = T), q25_ct_realized = quantile(catch_realized, 0.25, names = F, na.rm = T), q75_ct_realized = quantile(catch_realized, 0.75, names = F, na.rm = T))) + 
    geom_ribbon(aes(manage_val/1e+3, ymin = q25_ct_realized/1e+3, ymax = q75_ct_realized/1e+3, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)')), group = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)'))), fill = 'transparent', size = 0.3, linetype = 'dashed') + 
    geom_line(aes(manage_val/1e+3, md_ct_realized/1e+3, color = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)')), group = factor(decade_class, levels = c('Mid-century (2030-2049)', 'Late century (2050-2099)')))) + 
    geom_abline(intercept = 0, slope = 1, linetype = 'dashed', color = 'grey') + 
    xlab('Intended catch [kt]') + ylab('Realized catch [kt]') + scale_color_viridis(direction = -1, 'Period', option = 'plasma', discrete = T, begin = 0.2, end = 0.8) + theme_bw() + theme(text = element_text(size = 15)) + xlim(c(0,max(dat$manage_val[dat$manage_cat == 'catch'])/1e+3)) + ylim(c(0,max(dat$manage_val[dat$manage_cat == 'catch'])/1e+3)) # plot the median level and 25- and 75-% quantiles of realized catch against the level of intended catch. It becomes apparent that realized catch is close to zero, indicating that instances where realized catch diverges from intended catch are associated with permanent stock collapse
```

```{r}
# 11) Plots for scenario discovery

dat$gamma[dat$sr_mod == 'beverton holt'] <- -1 * dat$gamma[dat$sr_mod == 'beverton holt'] # sign of "gamma" SR parameter is changed for parameters of the Beverton-Holt model to make plots more comparable between SR models

dat$RCP <- as.character(dat$RCP)
dat$RCP[dat$RCP == 'sst45'] <- 'RCP4.5'
dat$RCP[dat$RCP == 'sst85'] <- 'RCP8.5'
```

```{r}
p1 <- ggplot(data = dat%>%ungroup()%>%filter(sr_mod == 'beverton holt' & manage_cat == 'catch')%>%select(year, alpha, beta, gamma, RCP, manage_val, risk_both)%>%distinct()%>%group_by(alpha, beta, gamma, RCP, manage_val)%>%summarize(is_not_risk = as.numeric((FALSE %in% risk_both) & (!TRUE %in% risk_both)))%>%filter(is_not_risk == T)%>%distinct(), aes(x = manage_val/1000, y = alpha)) 
p1 <- p1 + geom_point(aes(color = RCP, size = gamma), alpha = 0.25) 
p1 <- p1 + scale_size(expression(gamma), range = c(0.5, 5))  # Adjust the range of points size
p1 <- p1 +  scale_color_manual(values = c("#0d0887", "#f89540")) 
p1 <- p1 + xlab("Catch [kt]") + ylab(expression(paste('log(',alpha,')')))
p1 <- p1 + coord_cartesian(xlim=c(0,100), ylim = c(8.5,13.5))
p1 <- p1 + theme_linedraw()
p1 <- p1 + theme(legend.position = c(0.85,0.4))
p1

p1a <- ggMarginal(p1, margins = 'x', type="density", xparams = list(  bins=100), fill="grey",
                  col="black")
p1a # for each of the two SR models, plot every combination of policy lever and SR-parameter value (in this case, fixed catch and log_alpha, respectively) that yield a fully sustainable projection time series (i.e., SSB always above MSY Btrigger and Fbar always equal to or lower than Fmsy). Here for fixed catch and the Beverton-Holt model

p1 <- ggplot(data = dat%>%ungroup()%>%filter(sr_mod == 'ricker' & manage_cat == 'catch')%>%select(year, alpha, beta, gamma, RCP, manage_val, risk_both)%>%distinct()%>%group_by(alpha, beta, gamma, RCP, manage_val)%>%summarize(is_not_risk = as.numeric((FALSE %in% risk_both) & (!TRUE %in% risk_both)))%>%filter(is_not_risk == T)%>%distinct(), aes(x = manage_val/1000, y = alpha)) 
p1 <- p1 + geom_point(aes(color = RCP, size = gamma), alpha = 0.25) 
p1 <- p1 + scale_size(expression(gamma), range = c(0.5, 5))  # Adjust the range of points size
p1 <- p1 +  scale_color_manual(values = c("#0d0887", "#f89540")) 
p1 <- p1 + xlab("Catch [kt]") + ylab(expression(paste('log(',alpha,')')))
p1 <- p1 + coord_cartesian(xlim=c(0,100), ylim = c(8,12.25))
p1 <- p1 + theme_linedraw()
p1 <- p1 + theme(legend.position = 'none')
p1

p2a <- ggMarginal(p1, margins = 'x', type="density", xparams = list(  bins=100), fill="grey",
                  col="black")
p2a # the same for fixed catch and the Ricker model

p1 <- ggplot(data = dat%>%ungroup()%>%filter(sr_mod == 'beverton holt' & manage_cat == 'harvest')%>%select(year, alpha, beta, gamma, RCP, manage_val, risk_both)%>%distinct()%>%group_by(alpha, beta, gamma, RCP, manage_val)%>%summarize(is_not_risk = as.numeric((FALSE %in% risk_both) & (!TRUE %in% risk_both)))%>%filter(is_not_risk == T)%>%distinct(), aes(x = manage_val*100, y = alpha)) 
p1 <- p1 + geom_point(aes(color = RCP, size = gamma), alpha = 0.25) 
p1 <- p1 + scale_size(expression(gamma), range = c(0.5, 5))  # Adjust the range of points size
p1 <- p1 +  scale_color_manual(values = c("#0d0887", "#f89540")) 
p1 <- p1 + xlab("Harvest rate [%]") + ylab(expression(paste('log(',alpha,')')))
p1 <- p1 + coord_cartesian(xlim=c(0,25), ylim = c(8.5,13.5))
p1 <- p1 + theme_linedraw()
p1 <- p1 + theme(legend.position = 'none')
p1

p3a <- ggMarginal(p1, margins = 'x', type="density", xparams = list(  bins=100), fill="grey",
                  col="black")
p3a # the same for fixed harvest rate and the Beverton-Holt model

p1 <- ggplot(data = dat%>%ungroup()%>%filter(sr_mod == 'ricker' & manage_cat == 'harvest')%>%select(year, alpha, beta, gamma, RCP, manage_val, risk_both)%>%distinct()%>%group_by(alpha, beta, gamma, RCP, manage_val)%>%summarize(is_not_risk = as.numeric((FALSE %in% risk_both) & (!TRUE %in% risk_both)))%>%filter(is_not_risk == T)%>%distinct(), aes(x = manage_val*100, y = alpha)) 
p1 <- p1 + geom_point(aes(color = RCP, size = gamma), alpha = 0.25) 
p1 <- p1 + scale_size(expression(gamma), range = c(0.5, 5))  # Adjust the range of points size
p1 <- p1 +  scale_color_manual(values = c("#0d0887", "#f89540")) 
p1 <- p1 + xlab("Harvest rate [%]") + ylab(expression(paste('log(',alpha,')')))
p1 <- p1 + coord_cartesian(xlim=c(0,25), ylim = c(8,12.25))
p1 <- p1 + theme_linedraw()
p1 <- p1 + theme(legend.position = 'none')
p1

p4a <- ggMarginal(p1, margins = 'x', type="density", xparams = list(  bins=100), fill="grey",
                  col="black")
p4a # the same for fixed harvest rate and the Ricker model

tiff(filename = "/home/jan/PhD/EMA/North_Sea_Paper/scenario_discovery.tiff",
     width = 10,height = 10,compression = "lzw",res = 600, units = "in")
ggarrange(p1a,p2a,p3a,p4a, 
          labels = c("A","B","C","D"),
          ncol = 2, nrow = 2)
dev.off()
```

```{r}
print(c(min(dat$manage_val[dat$manage_cat == 'catch']) / 1e+3, unique(dat$sr_mod[dat$manage_val == min(dat$manage_val[dat$manage_cat == 'catch'])])))
print(c(min(dat$manage_val[dat$manage_cat == 'harvest']) * 100, unique(dat$sr_mod[dat$manage_val == min(dat$manage_val[dat$manage_cat == 'harvest'])])))

print(
  dat%>%ungroup()%>%filter(sr_mod == 'beverton holt' & manage_cat == 'catch')%>%select(year, alpha, beta, gamma, RCP, manage_val, risk_both)%>%distinct()%>%group_by(alpha, beta, gamma, RCP, manage_val)%>%summarize(is_not_risk = as.numeric((FALSE %in% risk_both) & (!TRUE %in% risk_both)))%>%ungroup()%>%filter(manage_val == min(manage_val))%>%summarize(perc_success = sum(is_not_risk == T) / sum(is_not_risk == is_not_risk) * 100)
)

print(
  dat%>%ungroup()%>%filter(sr_mod == 'beverton holt' & manage_cat == 'harvest')%>%select(year, alpha, beta, gamma, RCP, manage_val, risk_both)%>%distinct()%>%group_by(alpha, beta, gamma, RCP, manage_val)%>%summarize(is_not_risk = as.numeric((FALSE %in% risk_both) & (!TRUE %in% risk_both)))%>%ungroup()%>%filter(manage_val == min(manage_val))%>%summarize(perc_success = sum(is_not_risk == T) / sum(is_not_risk == is_not_risk) * 100)
) # display the minimum catch level and harvest rate tested and the corresponding relative amount of fully sustainable projections
```

```{r}
# 12) For feature-scoring analysis, see separate Python script
```

```{r}
# 13) References

# - Huang, B., Thorne, P. W., Banzon, V. F., Boyer, T., Chepurin, G., Lawrimore, J. H. et al. (2017). Extended Reconstructed Sea Surface Temperature, Version 5 (ERSSTv5): upgrades, validations, and intercomparisons. Journal of Climate, 30, 8179-8205
# - Peck, M. A., Catalán, I. A., Damalas, D., Elliott, M., Ferreira, J. G., Hamon, K. G. et al. (2020). Cllimate change and European fisheries and aquaculture. CERES Project Synthesis Report, Universität Hamburg, Hamburg (DE), 110 pp.
```

